sylius_grid:
    grids:
        nextstore_sylius_inventory_admin_inventory_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%nextstore_sylius_inventory.model.inventory_product.class%"
            sorting:
                createdAt: desc
            fields:
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                product:
                    type: twig
                    label: sylius.ui.product
                    options:
                        template: "@NextstoreSyliusInventoryPlugin/Admin/Inventory/Grid/Fields/_product.html.twig"
                productCode:
                    type: string
                    label: sylius.ui.code
                stock:
                    type: string
                    label: nextstore_sylius_inventory.ui.stock
                    sortable: ~
                warehouse:
                    type: twig
                    label: nextstore_sylius_inventory.ui.warehouse
                    options:
                        template: "@NextstoreSyliusInventoryPlugin/Admin/Inventory/Grid/Fields/_warehouse.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [productCode]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
