sylius_grid:
    grids:
        nextstore_sylius_inventory_admin_warehouse:
            driver:
                name: doctrine/orm
                options:
                    class: "%nextstore_sylius_inventory.model.warehouse.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                    sortable: ~
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                location:
                    type: string
                    label: sylius.ui.address
                    sortable: ~
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, name, location]
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
