imports:
    - { resource: resources/nextstore_inventory_movement.yaml }
    - { resource: resources/nextstore_inventory_movement_log.yaml }
    - { resource: resources/nextstore_inventory_movement_product.yaml }
    - { resource: resources/nextstore_inventory_product.yaml }
    - { resource: resources/nextstore_warehouse.yaml }
# - "@NextstoreSyliusInventoryPlugin/Resources/config/resources/nextstore_inventory_movement.yaml"
# - "@NextstoreSyliusInventoryPlugin/Resources/config/resources/nextstore_inventory_movement_log.yaml"
# - "@NextstoreSyliusInventoryPlugin/Resources/config/resources/nextstore_inventory_movement_product.yaml"
# - "@NextstoreSyliusInventoryPlugin/Resources/config/resources/nextstore_inventory_product.yaml"
# - "@NextstoreSyliusInventoryPlugin/Resources/config/resources/nextstore_warehouse.yaml"
