sylius_resource:
    resources:
        nextstore_sylius_inventory.inventory_product:
            driver: doctrine/orm
            classes:
                model: Nextstore\SyliusInventoryPlugin\Entity\InventoryProduct
                interface: Nextstore\SyliusInventoryPlugin\Entity\InventoryProductInterface
                repository: Nextstore\SyliusInventoryPlugin\Repository\Inventory\InventoryProductRepository
                factory: Sylius\Component\Resource\Factory\Factory
                form: Nextstore\SyliusInventoryPlugin\Form\Type\InventoryProductType
