sylius_resource:
    resources:
        nextstore_sylius_inventory.warehouse:
            driver: doctrine/orm
            classes:
                model: Nextstore\SyliusInventoryPlugin\Entity\Warehouse
                interface: Nextstore\SyliusInventoryPlugin\Entity\WarehouseInterface
                repository: Nextstore\SyliusInventoryPlugin\Repository\Inventory\WarehouseRepository
                factory: Sylius\Component\Resource\Factory\Factory
                form: Nextstore\SyliusInventoryPlugin\Form\Type\WarehouseType
